GRANT ALL ON DATABASE sem2025_gregoza TO sefmane WITH GRANT OPTION;
GRANT ALL ON SCHEMA public TO sefmane WITH GRANT OPTION;
GRANT ALL ON ALL TABLES IN SCHEMA public TO sefmane WITH GRANT OPTION;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO sefmane WITH GRANT OPTION;

GRANT CONNECT ON DATABASE sem2025_gregoza TO javnost;

GRANT ALL PRIVILEGES ON DATABASE sem2025_gregoza TO javnost;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO javnost;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO javnost;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO javnost;

GRANT ALL PRIVILEGES ON DATABASE sem2025_gregoza TO sefmane;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sefmane;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sefmane;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO sefmane;


--prihodnje pravice
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO sefmane;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO sefmane;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO sefmane;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO javnost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO javnost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO javnost;

-- javnost ne sme spreminjat tabel
REVOKE CREATE ON SCHEMA public FROM javnost;